name: biocollectapp
description: App para coleta biológica em campo

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Banco de dados local
  sqflite: ^2.3.0
  path_provider: ^2.1.1

  # Localização e imagens
  geolocator: ^10.1.0
  image_picker: ^1.0.4
  permission_handler: ^11.0.1

  # Excel e compartilhamento
  syncfusion_flutter_xlsio: ^23.1.36
  share_plus: ^7.2.1

  # Gerenciamento de estado e utilidades
  provider: ^6.0.5
  intl: ^0.18.1

    # Mapa
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

  # Ícones
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true